apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dagster-db-creds-static-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: dagster
  destination:
    create: true
    name: dagster-db-credentials
    transformation:
      excludeRaw: true
      includes:
        - username
        - password
  refreshAfter: 10s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dagster-db-creds-static-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: dagster
  destination:
    create: true
    name: dagster-db-credentials
    transformation:
      excludeRaw: true
      templates:
        postgresql-username:
          text: '{{- get .Secrets "username" -}}'
        postgresql-password:
          text: '{{- get .Secrets "password" -}}'
      includes:
        - username
        - password
  refreshAfter: 10s
