name: "homelab_dbt"
version: "1.0.0"
profile: "homelab_dbt"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  homelab_dbt:
    +properties:
      replication_num: "1"
    backblaze:
      +tags: ["backblaze"]
      gold:
        +materialized: table
        +schema: gold

seeds:
  +properties:
    replication_num: "1"
  +schema: bronze
