apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cdc-source-db
  namespace: pg-cdc-source-db
spec:
  instances: 1
  storage:
    size: 50Gi
    storageClass: local-path

  postgresql:
    parameters:
      wal_level: logical

  bootstrap:
    initdb:
      database: pg-cdc-source-db
      owner: pg-cdc
      secret:
        name: pg-cdc-source-db-credentials
