apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: ch-lab
spec:
  replicas: 1
  dataVolumeClaimSpec:
    storageClass: "longhorn"
    resources:
      requests:
        storage: 25Gi
---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: ch-lab
spec:
  replicas: 1
  dataVolumeClaimSpec:
    storageClass: "longhorn"
    resources:
      requests:
        storage: 150Gi
  keeperClusterRef:
    name: ch-lab
