apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: ch-lab
spec:
  replicas: 1
  dataVolumeClaimSpec:
    storageClassName: "longhorn"
    resources:
      requests:
        storage: 25Gi
---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: ch-lab
spec:
  replicas: 1
  dataVolumeClaimSpec:
    storageClassName: "longhorn"
    resources:
      requests:
        storage: 150Gi
  keeperClusterRef:
    name: ch-lab
  settings:
    defaultUserPassword:
      passwordType: sha256_password
      secret:
        name: ch-lab-credentials
        key: password
