apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ch-lab-db-creds-static-secret
  namespace: ch-lab
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: clickhouse
  destination:
    create: true
    name: ch-lab-credentials
    transformation:
      excludeRaw: true
      includes:
        - password
  refreshAfter: 10s
