apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pg-dwh
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: pg-dwh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  sources:
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      path: infra/pg-dwh/custom-resources
