FROM apache/airflow:3.2.1

USER root

# Install UV
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

USER airflow

RUN uv pip install --no-cache "apache-airflow==${AIRFLOW_VERSION}" \
  dbt-core \
  dbt-postgres \
  astronomer-cosmos \
  'apache-airflow[otel]' \
  apache-airflow-providers-openlineage[common.compat] \
  lxml \
  seaborn \
  openpyxl \
  toml \ 
  s3fs \
  pandas \
  polars \
  connectorx \
  adbc_driver_postgresql \
  psycopg2-binary \
  apache-airflow-providers-mysql
