apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  sources:
    - repoURL: https://seaweedfs.github.io/seaweedfs/helm
      chart: seaweedfs
      targetRevision: 4.0.393
      helm:
        valueFiles:
          - $lab/infra/seaweedfs/values.yaml
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      ref: lab
      targetRevision: HEAD
