apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: starrocks-db-sn
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: starrocks-db-sn
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      targetRevision: HEAD
      path: infra/starrocks-db-sn/custom-resources
