master:
  enabled: true
  replicas: 1
  affinity: ""

volume:
  enabled: true
  replicas: 1
  affinity: ""

  dataDirs:
    - name: data1
      type: "persistentVolumeClaim"
      size: "100Gi"
      storageClass: "local-path"
      maxVolumes: 0 # If set to zero, the limit will be auto configured

filer:
  enabled: true
  replicas: 1
  storage: 10Gi
  storageClass: null
  affinity: ""

  data:
    type: "persistentVolumeClaim"
    hostPathPrefix: /mnt/data
    claimName: seaweedfs-filer-pvc
    size: "10Gi"
    storageClass: "local-path"

  s3:
    enabled: true
    enableAuth: true
    existingConfigSecret: "sw-s3-auth-secret"

s3:
  enabled: true
  replicas: 1
  enableAuth: true
  existingConfigSecret: "sw-s3-auth-secret"
