apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Serikuly-Miras/lab.git
    targetRevision: HEAD
    path: infra/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
