apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seaweedfs-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
  hostnames:
    - "seaweedfs-filer.lab.s-miras.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - group: ""
          kind: Service
          name: seaweedfs-filer
          port: 8888
          weight: 1
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: seaweedfs-s3-route
spec:
  entryPoints:
    - seaweedfs-s3
  routes:
    - match: HostSNI(`*`)
      services:
        - name: seaweedfs-s3
          port: 8333
