apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vault-cnpg-db
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: "local-path"

  bootstrap:
    initdb:
      database: vault
      owner: vault
      secret:
        name: vault-db-credentials
      postInitApplicationSQL:
        - |
          CREATE TABLE vault_kv_store (
          parent_path TEXT COLLATE "C" NOT NULL,
            path        TEXT COLLATE "C",
            key         TEXT COLLATE "C",
            value       BYTEA,
            CONSTRAINT pkey PRIMARY KEY (path, key)
          );
        - CREATE INDEX parent_path_idx ON vault_kv_store (parent_path);
        - ALTER TABLE vault_kv_store OWNER TO vault;
  imagePullPolicy: Always
  plugins:
    - enabled: true
      name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: hetzner-object-store
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: hetzner-object-store
spec:
  configuration:
    destinationPath: s3://ms-homelab-cnpg-backups/
    endpointURL: https://nbg1.your-objectstorage.com
    s3Credentials:
      accessKeyId:
        name: hetzner-object-store-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: hetzner-object-store-secret
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
