apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: longhorn-system-backup-target-cert
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: longhorn
  destination:
    create: true
    name: longhorn-backup-target
    transformation:
      excludeRaw: true
      includes:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_ENDPOINTS
  refreshAfter: 30s
