apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.92.4
      helm:
        values: |
          apiServerProxyConfig:
            allowImpersonation: "false"
            mode: "true"

#
# tailscale requires client_id and client_secret for oauth
# those can be prepopulated (todo remplace with vault provider later)
# no need to change helm values file as the operator read them by default from operator-oauth
#
# kubectl create secret generic operator-oauth \
#                   --namespace tailscale \
#                   --from-literal=client_id='xxx' \
#                   --from-literal=client_secret='xxx'
#
