apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-postgres-exporter
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-postgres-exporter
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-postgres-exporter
      targetRevision: 7.1.1
      helm:
        valueFiles:
          - $lab/infra/prometheus-postgres-exporter/values.yaml
          - $lab/infra/prometheus-postgres-exporter/secret.yaml
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      ref: lab
      targetRevision: HEAD
