apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://dl.gitea.com/charts
      chart: gitea
      targetRevision: 12.5.3
      helm:
        valueFiles:
          - $lab/infra/gitea/values.yaml
    - repoURL: http://gitea-http.gitea.svc.cluster.local:3000/miras/lab
      ref: lab
      targetRevision: HEAD
    - repoURL: http://gitea-http.gitea.svc.cluster.local:3000/miras/lab
      path: infra/gitea/custom-resources
