apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
spec:
  instances: 3
  storage:
    size: 50Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: db-pooler-rw
spec:
  cluster:
    name: db
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: db-pooler-ro
spec:
  cluster:
    name: db
  instances: 3
  type: ro
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
