apiVersion: v1
kind: Service
metadata:
  name: db-pooler-rw-tcp
  namespace: db
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    cnpg.io/poolerName: db-pooler-rw
---
apiVersion: v1
kind: Service
metadata:
  name: db-pooler-ro-tcp
  namespace: db
spec:
  type: LoadBalancer
  ports:
    - port: 5433
      targetPort: 5432
      protocol: TCP
  selector:
    cnpg.io/poolerName: db-pooler-ro
