apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: db-pooler-ro
spec:
  cluster:
    name: db
  instances: 3
  type: ro
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
