apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pg-cdc-source-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: pg-cdc-source-db
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      targetRevision: HEAD
      path: infra/pg-cdc-source-db/custom-resources
