apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://strimzi.io/charts
      chart: strimzi-kafka-operator
      targetRevision: 1.0.0
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      targetRevision: HEAD
      path: infra/strimzi-kafka/custom-resources
    - repoURL: https://ui.charts.kafbat.io/
      chart: kafka-ui
      helm:
        values: |
          yamlApplicationConfig: {}
      targetRevision: 1.6.4
