FROM jupyter/datascience-notebook:x86_64-ubuntu-22.04

RUN pip install --no-cache-dir \
    nbgitpuller \
    polars \
    pandas \
    boto3 \
    s3fs \
    matplotlib \
    seaborn \
    scikit-learn \
    jupyterlab-git \
    jupyterlab-lsp \
    jupyterlab_code_formatter \
    'python-lsp-server[all]' \
    black \
    isort \
    autopep8 \
    yapf \
    flake8 \
    pylint \
    jupyterhub-firstuseauthenticator \
    dotenv
