apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: trino
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - chart: trino
      repoURL: https://trinodb.github.io/charts
      targetRevision: 1.42.2
      helm:
        valueFiles:
          - $lab/infra/trino/values.yaml
    - repoURL: http://gitea-http.gitea.svc.cluster.local:3000/miras/lab
      ref: lab
      targetRevision: HEAD
    - repoURL: http://gitea-http.gitea.svc.cluster.local:3000/miras/lab
      path: infra/trino/custom-resources
