apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: trino
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - chart: trino
      repoURL: https://trinodb.github.io/charts
      targetRevision: 1.42.1
      helm:
        values: |
          server:
            workers: 1
          image:
            tag: latest
          additionalConfigProperties:
            - http-server.process-forwarded=true
          envFrom:
            - secretRef:
                name: iceberg-catalog-credentials
            - secretRef:
                name: iceberg-s3-credentials
            - secretRef:
                name: postgres-dwh-credentials
            - secretRef:
                name: clickhouse-credentials
          catalogs:
            iceberg: |
              connector.name=iceberg
              iceberg.catalog.type=jdbc
              iceberg.jdbc-catalog.catalog-name=iceberg-catalog
              iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
              iceberg.jdbc-catalog.connection-url=jdbc:postgresql://iceberg-catalog-cnpg-db-rw.iceberg-catalog:5432/iceberg-catalog
              iceberg.jdbc-catalog.connection-user=${ENV:ICEBERG_CATALOG_USERNAME}
              iceberg.jdbc-catalog.connection-password=${ENV:ICEBERG_CATALOG_PASSWORD}
              iceberg.jdbc-catalog.default-warehouse-dir=s3://iceberg
              fs.hadoop.enabled=false
              fs.native-s3.enabled=true
              s3.path-style-access=true
              s3.endpoint=http://seaweedfs-s3.seaweedfs:8333
              s3.aws-access-key=${ENV:S3_AWS_ACCESS_KEY}
              s3.aws-secret-key=${ENV:S3_AWS_SECRET_KEY}
              s3.region=us-east-1
            postgresql-dwh: |
              connector.name=postgresql
              connection-url=jdbc:postgresql://dwh-cnpg-db-rw.dwh:5432/dwh
              connection-user=${ENV:POSTGRESQL_DWH_USERNAME}
              connection-password=${ENV:POSTGRESQL_DWH_PASSWORD}
            clickhouse: |
              connector.name=clickhouse
              connection-url=jdbc:clickhouse://ch-lab-clickhouse-headless.clickhouse:8123/
              connection-user=${ENV:CLICKHOUSE_USERNAME}
              connection-password=${ENV:CLICKHOUSE_PASSWORD}
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      path: infra/trino/custom-resources
