server:
  workers: 1
coordinator:
  jvm:
    maxHeapSize: "3584M"
  resources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 1
      memory: 4Gi
worker:
  jvm:
    maxHeapSize: "3584M"
  resources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 1
      memory: 4Gi
additionalConfigProperties:
  - http-server.process-forwarded=true
catalogs: {}
