---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "services", "endpoints"]
    verbs: ["get", "watch", "list", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink
subjects:
  - kind: ServiceAccount
    name: flink
---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: pg-cdc-session
spec:
  image: serikulymiras/flink:1.20.pg.str.s3
  flinkVersion: v1_20
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    execution.checkpointing.interval: "30s"
    state.backend: hashmap
    state.checkpoints.dir: s3://flink/checkpoints/pg-cdc-to-starrocks
    fs.s3a.endpoint: ${AWS_ENDPOINTS}
    fs.s3a.access.key: ${AWS_ACCESS_KEY_ID}
    fs.s3a.secret.key: ${AWS_SECRET_ACCESS_KEY}
    fs.s3a.path.style.access: "true"
    fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          envFrom:
            - secretRef:
                name: s3-flink-secret
          env:
            - name: AWS_ENDPOINTS
              valueFrom:
                secretKeyRef:
                  name: s3-flink-secret
                  key: AWS_ENDPOINTS
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-flink-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-flink-secret
                  key: AWS_SECRET_ACCESS_KEY
  serviceAccount: flink
  jobManager:
    resource:
      memory: "1024m"
      cpu: 1
  taskManager:
    resource:
      memory: "1024m"
      cpu: 1
