---
apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: starrocks-sink-users
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    strimzi.io/cluster: debezium-connect
spec:
  class: com.starrocks.connector.kafka.StarRocksSinkConnector
  tasksMax: 1
  config:
    topics: pg-cdc-source-db.public.users
    starrocks.http.url: starrocks-db-cluster-fe-service.starrocks-db.svc.cluster.local:8030
    starrocks.jdbc.url: jdbc:mysql://starrocks-db-cluster-fe-service.starrocks-db.svc.cluster.local:9030
    starrocks.username: root
    starrocks.password: ""
    starrocks.database.name: cdc
    starrocks.table.name: users
    starrocks.topic2table.map: pg-cdc-source-db.public.users:users
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://confluent-schema-registry.kafka.svc.cluster.local:8081
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://confluent-schema-registry.kafka.svc.cluster.local:8081
    transforms: addfield,unwrap
    transforms.addfield.type: com.starrocks.connector.kafka.transforms.AddOpFieldForDebeziumRecord
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: "true"
    transforms.unwrap.delete.handling.mode: rewrite
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: starrocks-sink-shops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    strimzi.io/cluster: debezium-connect
spec:
  class: com.starrocks.connector.kafka.StarRocksSinkConnector
  tasksMax: 1
  config:
    topics: pg-cdc-source-db.public.shops
    starrocks.http.url: starrocks-db-cluster-fe-service.starrocks-db.svc.cluster.local:8030
    starrocks.jdbc.url: jdbc:mysql://starrocks-db-cluster-fe-service.starrocks-db.svc.cluster.local:9030
    starrocks.username: root
    starrocks.password: ""
    starrocks.database.name: cdc
    starrocks.table.name: shops
    starrocks.topic2table.map: pg-cdc-source-db.public.shops:shops
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://confluent-schema-registry.kafka.svc.cluster.local:8081
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://confluent-schema-registry.kafka.svc.cluster.local:8081
    transforms: addfield,unwrap
    transforms.addfield.type: com.starrocks.connector.kafka.transforms.AddOpFieldForDebeziumRecord
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: "true"
    transforms.unwrap.delete.handling.mode: rewrite
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: starrocks-sink-orders
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    strimzi.io/cluster: debezium-connect
spec:
  class: com.starrocks.connector.kafka.StarRocksSinkConnector
  tasksMax: 1
  config:
    topics: pg-cdc-source-db.public.orders
    starrocks.http.url: starrocks-db-cluster-fe-service.starrocks-db.svc.cluster.local:8030
    starrocks.jdbc.url: jdbc:mysql://starrocks-db-cluster-fe-service.starrocks-db.svc.cluster.local:9030
    starrocks.username: root
    starrocks.password: ""
    starrocks.database.name: cdc
    starrocks.table.name: orders
    starrocks.topic2table.map: pg-cdc-source-db.public.orders:orders
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://confluent-schema-registry.kafka.svc.cluster.local:8081
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://confluent-schema-registry.kafka.svc.cluster.local:8081
    transforms: addfield,unwrap
    transforms.addfield.type: com.starrocks.connector.kafka.transforms.AddOpFieldForDebeziumRecord
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: "true"
    transforms.unwrap.delete.handling.mode: rewrite
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: starrocks-sink-meteo-data
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    strimzi.io/cluster: debezium-connect
spec:
  class: com.starrocks.connector.kafka.StarRocksSinkConnector
  tasksMax: 1
  config:
    topics: mssql-cdc-source-db.DWH.dbo.meteo_data
    starrocks.http.url: starrocks-db-cluster-fe-service.starrocks-db.svc.cluster.local:8030
    starrocks.jdbc.url: jdbc:mysql://starrocks-db-cluster-fe-service.starrocks-db.svc.cluster.local:9030
    starrocks.username: root
    starrocks.password: ""
    starrocks.database.name: cdc
    starrocks.table.name: meteo_data
    starrocks.topic2table.map: mssql-cdc-source-db.DWH.dbo.meteo_data:meteo_data
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://confluent-schema-registry.kafka.svc.cluster.local:8081
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://confluent-schema-registry.kafka.svc.cluster.local:8081
    transforms: addfield,unwrap
    transforms.addfield.type: com.starrocks.connector.kafka.transforms.AddOpFieldForDebeziumRecord
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: "true"
    transforms.unwrap.delete.handling.mode: rewrite
    sink.properties.strip_outer_array: "true"
