apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: debezium-connect
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
    argocd.argoproj.io/sync-wave: "1"
spec:
  version: 4.2.0
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  image: serikulymiras/kafka-connect-debezium:1.0.0-kafka-4.2.0-dbz-3.4.3-str-avro
  template:
    connectContainer:
      env:
        - name: PG_CDC_USERNAME
          valueFrom:
            secretKeyRef:
              name: pg-cdc-source-db-credentials-kafka
              key: username
        - name: PG_CDC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-cdc-source-db-credentials-kafka
              key: password
  groupId: debezium-connect-cluster
  offsetStorageTopic: debezium-connect-offsets
  configStorageTopic: debezium-connect-configs
  statusStorageTopic: debezium-connect-status
  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    config.providers: env
    config.providers.env.class: org.apache.kafka.common.config.provider.EnvVarConfigProvider
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://schema-registry.kafka.svc.cluster.local:8081
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://schema-registry.kafka.svc.cluster.local:8081
