apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=false # create ns and seed creds beforehand
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.32.0
      helm:
        values: |
          server:
            extraArgs: "-config=/vault/userconfig/vault-storage-config/config.hcl"
            volumes:
              - name: userconfig-vault-storage-config
                secret:
                  secretName: vault-storage-config
                  defaultMode: 420
            volumeMounts:
              - name: userconfig-vault-storage-config
                mountPath: /vault/userconfig/vault-storage-config
                readOnly: true
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      targetRevision: HEAD
      path: infra/vault/custom-resources
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates

# dont forget to seed db creds and vault config
# config.hcl <<
# storage "postgresql" {
#     connection_url = "postgres://vault:secret123!@vault-cnpg-db-rw.vault:5432/vault"
# }
# kubectl create secret generic vault-db-credentials --from-literal=username=vault --from-literal=password=secret123! -n vault
# kubectl create secret generic vault-storage-config --from-file=config.hcl -n vault
# kubectl create secret generic hetzner-object-store-secret --from-literal=ACCESS_KEY_ID=your_access_key_id --from-literal=ACCESS_SECRET_KEY=your_secret_access_key -n vault
