global:
  postgresqlSecretName: dagster-db-credentials-remapped

postgresql:
  enabled: false
  postgresqlHost: dagster-cnpg-db-rw.dagster
  postgresqlUsername: dagster
  postgresqlDatabase: dagster
  postgresqlParams: {}
  postgresqlScheme: ""
  postgresqlPassword: ""
generatePostgresqlPasswordSecret: false

telemetry:
  enabled: false

dagster-user-deployments:
  enabled: true
  deployments:
    - name: dgstr
      image:
        repository: serikulymiras/dagster
        tag: homelab-v6
        pullPolicy: IfNotPresent
      dagsterApiGrpcArgs:
        - "-m"
        - "dgstr.definitions"
      port: 3030
      envSecrets: []
