global:
  postgresqlSecretName: dagster-db-credentials

postgresql:
  enabled: false
  postgresqlHost: dagster-cnpg-db-rw.dagster
  postgresqlUsername: dagster
  postgresqlDatabase: dagster
  postgresqlParams: {}
  postgresqlScheme: ""
  postgresqlPassword: ""
generatePostgresqlPasswordSecret: false

telemetry:
  enabled: false

