apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitea-admin-creds-static-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: gitea
  destination:
    create: true
    name: gitea-admin-credentials
    transformation:
      templates:
        username:
          text: '{{- get .Secrets "gitea_admin_username" -}}'
        password:
          text: '{{- get .Secrets "gitea_admin_password" -}}'
      excludeRaw: true
  refreshAfter: 10s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitea-valkey-creds-static-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: gitea
  destination:
    create: true
    name: gitea-valkey-credentials
    transformation:
      excludeRaw: true
      includes:
        - gitea_valkey_password
  refreshAfter: 10s
