apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault-secrets-operator
      targetRevision: 0.10.0
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      ref: custom-resources
      targetRevision: HEAD
      path: infra/vault-secrets-operator/custom-resources
