apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault-secrets-operator
      targetRevision: 0.10.0
      helm:
        valueFiles:
          - $lab/infra/vault-secrets-operator/sa.yaml
          - $lab/infra/vault-secrets-operator/vc.yaml
          - $lab/infra/vault-secrets-operator/va.yaml
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      ref: lab
      targetRevision: HEAD
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      ref: lab
      targetRevision: HEAD
      path: infra/vault-secrets-operator/custom-resources
