CREATE TABLE IF NOT EXISTS { database }.{ TABLE } (
    `date` DATE NOT NULL,
    serial_number VARCHAR(32) NOT NULL,
    model VARCHAR(64) NOT NULL,
    capacity_bytes bigint NOT NULL,
    failure bigint NOT NULL,
    datacenter VARCHAR(64) NOT NULL,
    cluster_id bigint NOT NULL,
    vault_id bigint NOT NULL,
    pod_id bigint NOT NULL,
    pod_slot_num bigint NOT NULL,
    is_legacy_format BOOLEAN NOT NULL,
    smart_1_normalized bigint NULL,
    smart_1_raw bigint NULL,
    smart_2_normalized bigint NULL,
    smart_2_raw bigint NULL,
    smart_3_normalized bigint NULL,
    smart_3_raw bigint NULL,
    smart_4_normalized bigint NULL,
    smart_4_raw bigint NULL,
    smart_5_normalized bigint NULL,
    smart_5_raw bigint NULL,
    smart_7_normalized bigint NULL,
    smart_7_raw bigint NULL,
    smart_8_normalized bigint NULL,
    smart_8_raw bigint NULL,
    smart_9_normalized bigint NULL,
    smart_9_raw bigint NULL,
    smart_10_normalized bigint NULL,
    smart_10_raw bigint NULL,
    smart_11_normalized bigint NULL,
    smart_11_raw bigint NULL,
    smart_12_normalized bigint NULL,
    smart_12_raw bigint NULL,
    smart_13_normalized bigint NULL,
    smart_13_raw bigint NULL,
    smart_15_normalized bigint NULL,
    smart_15_raw bigint NULL,
    smart_16_normalized bigint NULL,
    smart_16_raw bigint NULL,
    smart_17_normalized bigint NULL,
    smart_17_raw bigint NULL,
    smart_18_normalized bigint NULL,
    smart_18_raw bigint NULL,
    smart_22_normalized bigint NULL,
    smart_22_raw bigint NULL,
    smart_23_normalized bigint NULL,
    smart_23_raw bigint NULL,
    smart_24_normalized bigint NULL,
    smart_24_raw bigint NULL,
    smart_27_normalized bigint NULL,
    smart_27_raw bigint NULL,
    smart_71_normalized bigint NULL,
    smart_71_raw bigint NULL,
    smart_82_normalized bigint NULL,
    smart_82_raw bigint NULL,
    smart_90_normalized bigint NULL,
    smart_90_raw bigint NULL,
    smart_160_normalized bigint NULL,
    smart_160_raw bigint NULL,
    smart_161_normalized bigint NULL,
    smart_161_raw bigint NULL,
    smart_163_normalized bigint NULL,
    smart_163_raw bigint NULL,
    smart_164_normalized bigint NULL,
    smart_164_raw bigint NULL,
    smart_165_normalized bigint NULL,
    smart_165_raw bigint NULL,
    smart_166_normalized bigint NULL,
    smart_166_raw bigint NULL,
    smart_167_normalized bigint NULL,
    smart_167_raw bigint NULL,
    smart_168_normalized bigint NULL,
    smart_168_raw bigint NULL,
    smart_169_normalized bigint NULL,
    smart_169_raw bigint NULL,
    smart_170_normalized bigint NULL,
    smart_170_raw bigint NULL,
    smart_171_normalized bigint NULL,
    smart_171_raw bigint NULL,
    smart_172_normalized bigint NULL,
    smart_172_raw bigint NULL,
    smart_173_normalized bigint NULL,
    smart_173_raw bigint NULL,
    smart_174_normalized bigint NULL,
    smart_174_raw bigint NULL,
    smart_175_normalized bigint NULL,
    smart_175_raw bigint NULL,
    smart_176_normalized bigint NULL,
    smart_176_raw bigint NULL,
    smart_177_normalized bigint NULL,
    smart_177_raw bigint NULL,
    smart_178_normalized bigint NULL,
    smart_178_raw bigint NULL,
    smart_179_normalized bigint NULL,
    smart_179_raw bigint NULL,
    smart_180_normalized bigint NULL,
    smart_180_raw bigint NULL,
    smart_181_normalized bigint NULL,
    smart_181_raw bigint NULL,
    smart_182_normalized bigint NULL,
    smart_182_raw bigint NULL,
    smart_183_normalized bigint NULL,
    smart_183_raw bigint NULL,
    smart_184_normalized bigint NULL,
    smart_184_raw bigint NULL,
    smart_187_normalized bigint NULL,
    smart_187_raw bigint NULL,
    smart_188_normalized bigint NULL,
    smart_188_raw bigint NULL,
    smart_189_normalized bigint NULL,
    smart_189_raw bigint NULL,
    smart_190_normalized bigint NULL,
    smart_190_raw bigint NULL,
    smart_191_normalized bigint NULL,
    smart_191_raw bigint NULL,
    smart_192_normalized bigint NULL,
    smart_192_raw bigint NULL,
    smart_193_normalized bigint NULL,
    smart_193_raw bigint NULL,
    smart_194_normalized bigint NULL,
    smart_194_raw bigint NULL,
    smart_195_normalized bigint NULL,
    smart_195_raw bigint NULL,
    smart_196_normalized bigint NULL,
    smart_196_raw bigint NULL,
    smart_197_normalized bigint NULL,
    smart_197_raw bigint NULL,
    smart_198_normalized bigint NULL,
    smart_198_raw bigint NULL,
    smart_199_normalized bigint NULL,
    smart_199_raw bigint NULL,
    smart_200_normalized bigint NULL,
    smart_200_raw bigint NULL,
    smart_201_normalized bigint NULL,
    smart_201_raw bigint NULL,
    smart_202_normalized bigint NULL,
    smart_202_raw bigint NULL,
    smart_206_normalized bigint NULL,
    smart_206_raw bigint NULL,
    smart_210_normalized bigint NULL,
    smart_210_raw bigint NULL,
    smart_211_normalized bigint NULL,
    smart_211_raw bigint NULL,
    smart_212_normalized bigint NULL,
    smart_212_raw bigint NULL,
    smart_218_normalized bigint NULL,
    smart_218_raw bigint NULL,
    smart_220_normalized bigint NULL,
    smart_220_raw bigint NULL,
    smart_222_normalized bigint NULL,
    smart_222_raw bigint NULL,
    smart_223_normalized bigint NULL,
    smart_223_raw bigint NULL,
    smart_224_normalized bigint NULL,
    smart_224_raw bigint NULL,
    smart_225_normalized bigint NULL,
    smart_225_raw bigint NULL,
    smart_226_normalized bigint NULL,
    smart_226_raw bigint NULL,
    smart_230_normalized bigint NULL,
    smart_230_raw bigint NULL,
    smart_231_normalized bigint NULL,
    smart_231_raw bigint NULL,
    smart_232_normalized bigint NULL,
    smart_232_raw bigint NULL,
    smart_233_normalized bigint NULL,
    smart_233_raw bigint NULL,
    smart_234_normalized bigint NULL,
    smart_234_raw bigint NULL,
    smart_235_normalized bigint NULL,
    smart_235_raw bigint NULL,
    smart_240_normalized bigint NULL,
    smart_240_raw bigint NULL,
    smart_241_normalized bigint NULL,
    smart_241_raw bigint NULL,
    smart_242_normalized bigint NULL,
    smart_242_raw bigint NULL,
    smart_244_normalized bigint NULL,
    smart_244_raw bigint NULL,
    smart_245_normalized bigint NULL,
    smart_245_raw bigint NULL,
    smart_246_normalized bigint NULL,
    smart_246_raw bigint NULL,
    smart_247_normalized bigint NULL,
    smart_247_raw bigint NULL,
    smart_248_normalized bigint NULL,
    smart_248_raw bigint NULL,
    smart_250_normalized bigint NULL,
    smart_250_raw bigint NULL,
    smart_251_normalized bigint NULL,
    smart_251_raw bigint NULL,
    smart_252_normalized bigint NULL,
    smart_252_raw bigint NULL,
    smart_254_normalized bigint NULL,
    smart_254_raw bigint NULL,
    smart_255_normalized bigint NULL,
    smart_255_rawBIGINT NULL
) engine = olap primary key(
    `date`,
    serial_number
) PARTITION BY DATE_TRUNC(
    'day',
    `date`
) distributed BY HASH(serial_number) buckets 10 properties (
    "replication_num" = "1"
);
