name: "backblaze_starrocks"
version: "1.0.0"
profile: "backblaze_starrocks"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  backblaze_starrocks:
    +properties:
      replication_num: "1"
    marts:
      +materialized: table
      +schema: gold
    staging:
      +materialized: table
      +schema: silver
