apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  sources:
    - repoURL: https://airflow.apache.org/
      chart: airflow
      targetRevision: 1.18.0
      helm:
        valueFiles:
          - $lab/infra/airflow/values.yaml
          - $lab/infra/airflow/ingress.yaml
          - $lab/infra/airflow/logs_pvc.yaml
          - $lab/infra/airflow/secret.yaml
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      ref: lab
      targetRevision: HEAD
