apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
  sources:
    - repoURL: https://airflow.apache.org/
      chart: airflow
      targetRevision: 1.18.0
      helm:
        valueFiles:
          - $lab/infra/airflow/values.yaml
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      ref: lab
      targetRevision: HEAD
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      targetRevision: HEAD
      path: infra/airflow/custom-resources
