apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-system-hetzner-s3-store
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: cnpg-hetzner-s3-store
  destination:
    create: true
    name: hetzner-object-store-secret
    transformation:
      excludeRaw: true
      includes:
        - ACCESS_KEY_ID
        - ACCESS_SECRET_KEY
  refreshAfter: 30s
