apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bytebase
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: bytebase
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - chart: bytebase
      repoURL: https://bytebase.github.io/bytebase/
      targetRevision: 1.1.2
      helm:
        values: |
          bytebase:
            option:
              port: 8080
              external-url: "https://bytebase.lab.s-miras.com"
              externalPg:
                pgHost: "bytebase-cnpg-db-rw.bytebase"
                pgPort: "5432"
                pgUsername: "bytebase"
                pgDatabase: "bytebase"
                existingPgPasswordSecret: "bytebase-db-credentials"
                existingPgPasswordSecretKey: "password"
            persistence:
              enabled: false
    - repoURL: https://gitea.lab.s-miras.com/miras/lab.git
      targetRevision: HEAD
      path: infra/bytebase/custom-resources
