apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true

      starrocks-db-sn-query-entrypoint:
        port: 9030
        exposedPort: 9030
        protocol: TCP
        expose:
          default: true

      pg-db-entrypoint:
        port: 5432
        exposedPort: 5432
        protocol: TCP
        expose:
          default: true

    providers:
      kubernetesGateway:
        enabled: true
      kubernetesCRD:
        enabled: true

    gateway:
      enabled: true
      listeners:
        websecure:
          protocol: HTTPS
          port: 8443
          hostname: "*.lab.s-miras.com"
          mode: Terminate
          namespacePolicy:
            from: All
          certificateRefs:
            - name: tls
              group: ""
              kind: Secret
