apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tls-vss
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: tls
  destination:
    create: true
    name: tls
    type: kubernetes.io/tls
    transformation:
      excludeRaw: true
      includes:
        - tls.crt
        - tls.key
  refreshAfter: 30s
