apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kaneo
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kaneo
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      path: infra/kaneo/chart
      helm:
        valueFiles:
          - $lab/infra/kaneo/values.yaml
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      ref: lab
      targetRevision: HEAD
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      path: infra/kaneo/custom-resources
      targetRevision: HEAD
