apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-setup
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://strimzi.io/charts
      chart: strimzi-kafka-operator
      targetRevision: 1.0.0
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      targetRevision: HEAD
      path: infra/streaming/strimzi-kafka/custom-resources
    - repoURL: https://ui.charts.kafbat.io/
      chart: kafka-ui
      helm:
        values: |
          yamlApplicationConfig:
            kafka:
              clusters:
                - name: yaml
                  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
                  kafkaConnect:
                    - name: debezium-connect
                      address: http://debezium-connect-connect-api.kafka.svc.cluster.local:8083
                  schemaRegistry: http://confluent-schema-registry.kafka.svc.cluster.local:8081
                  schemaRegistryType: CONFLUENT
                  defaultKeySerde: SchemaRegistry
                  defaultValueSerde: SchemaRegistry
            auth:
              type: disabled
            management:
              health:
                ldap:
                  enabled: false
      targetRevision: 1.6.4
