apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.0
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      ref: lab
      targetRevision: HEAD
      path: infra/vault/ingress
