preUpgradeChecker:
  jobEnabled: false

defaultSettings:
  defaultDataPath: /var/lib/rancher/k3s/longhorn
  defaultReplicaCount: 1

persistence:
  defaultClassReplicaCount: 1

httproute:
  enabled: true
  parentRefs:
    - name: traefik-gateway
      namespace: kube-system
      sectionName: websecure
  hostnames:
    - longhorn.lab.s-miras.com
