apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: clickhouse-vss
  namespace: trino
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: clickhouse
  destination:
    create: true
    name: clickhouse-credentials
    transformation:
      templates:
        CLICKHOUSE_USERNAME:
          text: '{{- get .Secrets "username" -}}'
        CLICKHOUSE_PASSWORD:
          text: '{{- get .Secrets "password" -}}'
      excludes:
        - .*
      excludeRaw: true
  refreshAfter: 30s
