apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-dwh-vss
  namespace: trino
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: dwh-db-etl-credentials
  destination:
    create: true
    name: postgres-dwh-credentials
    transformation:
      templates:
        POSTGRESQL_DWH_USERNAME:
          text: '{{- get .Secrets "username" -}}'
        POSTGRESQL_DWH_PASSWORD:
          text: '{{- get .Secrets "password" -}}'
      excludeRaw: true
  refreshAfter: 30s
