apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      targetRevision: 2.35.0
      helm:
        values: |
          persistentVolumeClaim:
            enabled: true
            accessModes:
              - ReadWriteOnce
            size: "1Gi"
          adminPassword: {}
          admin:
            enabled: true
            existingSecret: "pihole-admin-secret"
            passwordKey: "password"
    - repoURL: https://github.com/Serikuly-Miras/lab.git
      targetRevision: HEAD
      path: infra/pihole/custom-resources
