apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-kubernetes-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: flink-kubernetes-operator
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: flinkbluegreendeployments.flink.apache.org
      jqPathExpressions:
        - .spec.versions[].additionalPrinterColumns[]?.priority
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: flinkdeployments.flink.apache.org
      jqPathExpressions:
        - .spec.versions[].additionalPrinterColumns[]?.priority
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: flinksessionjobs.flink.apache.org
      jqPathExpressions:
        - .spec.versions[].additionalPrinterColumns[]?.priority
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: flinkstatesnapshots.flink.apache.org
      jqPathExpressions:
        - .spec.versions[].additionalPrinterColumns[]?.priority
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://downloads.apache.org/flink/flink-kubernetes-operator-1.14.0/
      chart: flink-kubernetes-operator
      targetRevision: 1.14.0
