apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dwh-pg-db-credentials-vss
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: dwh-pg-db-credentials
  destination:
    create: true
    name: dwh-pg-db-credentials
    transformation:
      excludeRaw: true
      includes:
        - username
        - password
  refreshAfter: 30s
