apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mssql-cdc-source-db-creds-static-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: mssql-cdc-source-db
  destination:
    create: true
    name: mssql-cdc-source-db-credentials
    transformation:
      excludeRaw: true
      includes:
        - MSSQL_SA_PASSWORD
  refreshAfter: 10s
