apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: tempo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: 1.24.1
      helm:
        values: |
          replicas: 1
          tempo:
            updateStrategy: RollingUpdate
            memBallastSizeMbs: 1024
            multitenancyEnabled: false
            reportingEnabled: false
            retention: 168h # week retention
          persistence:
            enabled: true
            storageClassName: custom-longhorn-slower-sc
            accessModes:
              - ReadWriteOnce
            size: 10Gi
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
