apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin-credentials-vss
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: grafana
  destination:
    create: true
    name: grafana-admin-credentials
    transformation:
      excludeRaw: true
      includes:
        - admin-user
        - admin-password
  refreshAfter: 30s
