apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: airflow-cnpg-db
spec:
  instances: 1
  storage:
    size: 20Gi

  bootstrap:
    initdb:
      database: airflow
      owner: airflow
      secret:
        name: airflow-db-credentials

  imagePullPolicy: Always
  plugins:
    - enabled: true
      name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: hetzner-object-store
