apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: airflow-git-credentials
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: airflow
  destination:
    create: true
    transformation:
      excludeRaw: true
      includes:
        - GITSYNC_USERNAME
        - GITSYNC_PASSWORD
      templates:
        GIT_SYNC_USERNAME:
          text: '{{- get .Secrets "GITSYNC_USERNAME" -}}'
        GIT_SYNC_PASSWORD:
          text: '{{- get .Secrets "GITSYNC_PASSWORD" -}}'
    name: airflow-git-credentials-secret
