apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: airflow-static-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: airflow
  destination:
    create: true
    name: airflow-vault-secret
    transformation:
      excludeRaw: true
      includes:
        - connection
        - fernet-key
        - jwt-secret
        - webserver-secret-key
  refreshAfter: 10s
