apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: hetzner-object-store
spec:
  configuration:
    destinationPath: s3://ms-homelab-cnpg-backups/
    endpointURL: https://nbg1.your-objectstorage.com
    s3Credentials:
      accessKeyId:
        name: hetzner-object-store-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: hetzner-object-store-secret
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-system-hetzner-s3-store
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: vault-auth
  mount: kvv2
  type: kv-v2
  path: cnpg-hetzner-s3-store
  destination:
    create: true
    name: hetzner-object-store-secret
    transformation:
      excludeRaw: true
      includes:
        - ACCESS_KEY_ID
        - ACCESS_SECRET_KEY
  refreshAfter: 30s
