apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dwh-cnpg-db
  namespace: dwh
spec:
  instances: 1
  storage:
    size: 200Gi
    storageClass: "local-path"

  bootstrap:
    initdb:
      database: dwh
      owner: dwh
      secret:
        name: dwh-db-credentials

  resources:
    requests:
      memory: "8Gi"
      cpu: '4'
    limits:
      memory: "8Gi"
      cpu: '4'

  # DB Version: 18
  # OS Type: linux
  # DB Type: dw
  # Total Memory (RAM): 8 GB
  # CPUs num: 4
  # Connections num: 30
  # Data Storage: ssd

  postgresql:
    parameters:
      max_connections: "30"
      shared_buffers: "2GB"
      effective_cache_size: "6GB"
      maintenance_work_mem: "1GB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "500"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "30840kB"
      huge_pages: "try"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      max_worker_processes: "4"
      max_parallel_workers_per_gather: "2"
      max_parallel_workers: "4"
      max_parallel_maintenance_workers: "2"

  managed:
    roles:
      - name: readonly
        ensure: present
        login: false
        superuser: false
        connectionLimit: -1
        inherit: true
      - name: readwrite
        ensure: present
        login: false
        superuser: false
        connectionLimit: -1
        inherit: true
        inRoles:
          - readonly
      - name: etl_user
        ensure: present
        login: true
        superuser: false
        connectionLimit: -1
        inherit: true
        inRoles:
          - readwrite
        passwordSecret:
          name: dwh-db-etl-credentials

  imagePullPolicy: Always
  plugins:
    - enabled: true
      name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: hetzner-object-store
