apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dwh-cnpg-db
  namespace: dwh
spec:
  instances: 2
  storage:
    size: 200Gi
    storageClass: custom-longhorn-faster-sc

  bootstrap:
    initdb:
      database: dwh
      owner: dwh
      secret:
        name: dwh-db-credentials

  managed:
    roles:
      - name: role-ro
        ensure: absent
      - name: role-rw
        ensure: absent
      - name: etl-user
        ensure: absent
      - name: readonly
        ensure: present
        login: false
        superuser: false
        connectionLimit: -1
        inherit: true
      - name: readwrite
        ensure: present
        login: false
        superuser: false
        connectionLimit: -1
        inherit: true
        inRoles:
          - readonly
      - name: etl_user
        ensure: present
        login: true
        superuser: false
        connectionLimit: -1
        inherit: true
        inRoles:
          - readwrite
        passwordSecret:
          name: dwh-db-etl-credentials
