apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakekeeper
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: lakekeeper
  ignoreDifferences:
    - kind: Secret
      name: lakekeeper-postgres-encryption
      namespace: lakekeeper
      jsonPointers:
        - /data
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://lakekeeper.github.io/lakekeeper-charts/
      chart: lakekeeper
      targetRevision: 0.11.0
      helm:
        valueFiles:
          - $lab/infra/lakekeeper/values.yaml
    - repoURL: http://gitea-http.gitea.svc.cluster.local:3000/miras/lab
      ref: lab
      targetRevision: HEAD
    - repoURL: http://gitea-http.gitea.svc.cluster.local:3000/miras/lab
      targetRevision: HEAD
      path: infra/lakekeeper/custom-resources
