lakekeeper:
  edition: "core"
  licenseKey: ""
  replicas: &catalog_replicas 1
  resources: {}

postgresql:
  enabled: false

externalDatabase:
  type: postgres
  host_read: lakekeeper-catalog-cnpg-db-r.lakekeeper.svc.cluster.local
  host_write: lakekeeper-catalog-cnpg-db-rw.lakekeeper.svc.cluster.local
  port: 5432
  database: catalog
  user: catalog
  userSecret: lakekeeper-catalog-cnpg-db-credentials
  userSecretKey: "username"
  passwordSecret: lakekeeper-catalog-cnpg-db-credentials
  passwordSecretKey: "password"
