version: 2

models:
  - name: dim_backblaze_datacenter
    description: "Normalized datacenter dimension table"
    columns:
      - name: datacenter_id
        description: "Surrogate key for datacenter"
        data_tests:
          - unique
          - not_null
      - name: datacenter
        description: "Datacenter name"
        data_tests:
          - unique
          - not_null

  - name: dim_backblaze_disk_model
    description: "Normalized disk model dimension table"
    columns:
      - name: model_id
        description: "Surrogate key for disk model"
        data_tests:
          - unique
          - not_null
      - name: model
        description: "Disk model name"
        data_tests:
          - unique
          - not_null
          - dbt_utils.not_empty_string
      - name: manufacturer
        description: "Disk manufacturer name"
        data_tests:
          - dbt_utils.not_empty_string
    data_tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "manufacturer != 'Other'"

  - name: fact_backblaze
    description: "Fact table for Backblaze disk data"
    columns:
      - name: date
        description: "Date of the observation"
        data_tests:
          - not_null
      - name: serial_number
        description: "Unique identifier for the disk"
        data_tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - date
              - serial_number

  - name: fact_backblaze_smart
    description: "Fact table for Backblaze SMART attributes data"
    columns:
      - name: date
        description: "Date of the observation"
        data_tests:
          - not_null
      - name: serial_number
        description: "Unique identifier for the disk"
        data_tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - date
              - serial_number
